#@ECHO OFF
CLS
del /q "D:\AUTOMACAO\BANCOS\CASES\SIGAWEAR.FDB"
del /q "D:\AUTOMACAO\BANCOS\CASES\SIGAPDV.FDB"
"C:\Program Files\WinRAR\rar.exe" -df x -y D:\AUTOMACAO\BANCOS\CASES\SIGAWEAR.rar D:\AUTOMACAO\BANCOS\CASES
"C:\Program Files\WinRAR\rar.exe" -df x -y D:\AUTOMACAO\BANCOS\CASES\SIGAPDV.rar  D:\AUTOMACAO\BANCOS\CASES
