#@ECHO OFF
CLS
del /q "D:\AUTOMACAO\BANCOS\GAROTAMIMADA\SIGAWEAR\SIGAWEAR.FDB"
"C:\Program Files\WinRAR\rar.exe" -df x -y D:\AUTOMACAO\BANCOS\GAROTAMIMADA\SIGAWEAR.rar D:\AUTOMACAO\BANCOS\GAROTAMIMADA
