#@ECHO OFF
CLS
del /q "D:\AUTOMACAO\BANCOS\UNIVERSETEEN\SIGAWEAR.FDB"
del /q "D:\AUTOMACAO\BANCOS\UNIVERSETEEN\SIGAPDV.FDB"
"C:\Program Files\WinRAR\rar.exe" -df x -y D:\AUTOMACAO\BANCOS\UNIVERSETEEN\SIGAWEAR.rar D:\AUTOMACAO\BANCOS\UNIVERSETEEN
"C:\Program Files\WinRAR\rar.exe" -df x -y D:\AUTOMACAO\BANCOS\UNIVERSETEEN\SIGAPDV.rar  D:\AUTOMACAO\BANCOS\UNIVERSETEEN
